/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.navisu.charts;

import gov.nasa.worldwindx.examples.BulkDownloadPanel;
import java.awt.BorderLayout;
import org.navisu.core.WorldWindManagerServices;
import org.navisu.core.impl.WorldWindManager;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Lookup;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.navisu.charts//BulkDownload//EN",
        autostore = false)
@TopComponent.Description(
        preferredID = "BulkDownloadTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "leftSlidingSide", openAtStartup = false)
@ActionID(category = "Window", id = "org.navisu.charts.BulkDownloadTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_BulkDownloadAction",
        preferredID = "BulkDownloadTopComponent")
@Messages({
    "CTL_BulkDownloadAction=BulkDownload",
    "CTL_BulkDownloadTopComponent=BulkDownload Window",
    "HINT_BulkDownloadTopComponent=This is a BulkDownload window"
})
public final class BulkDownloadTopComponent extends TopComponent {

    protected BulkDownloadPanel bulkDownloadPanel;

    public BulkDownloadTopComponent() {
        initComponents();
        setName(Bundle.CTL_BulkDownloadTopComponent());
        setToolTipText(Bundle.HINT_BulkDownloadTopComponent());

        this.bulkDownloadPanel = new  BulkDownloadPanel(Lookup.getDefault().lookup(WorldWindManagerServices.class).getWorldWindow());
        this.add(this.bulkDownloadPanel, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
       
       //System.out.println("++++++++++++" +Lookup.getDefault().lookup(WorldWindManager.class).getWorldWindow());
       //add(BorderLayout.CENTER, bulkDownloadPanel);
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
