/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.navisu.parameters;

import org.openide.util.NbPreferences;

final public class MainShipPanel
        extends javax.swing.JPanel {

    private final MainShipOptionsPanelController controller;

    MainShipPanel(MainShipOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameJTF = new javax.swing.JTextField();
        mmsiJTF = new javax.swing.JTextField();
        imoJTF = new javax.swing.JTextField();
        widthJTF = new javax.swing.JTextField();
        lengthJTF = new javax.swing.JTextField();
        draughtJTF = new javax.swing.JTextField();
        model3DJTF = new javax.swing.JTextField();
        destinationJTF = new javax.swing.JTextField();
        etaJTF = new javax.swing.JTextField();
        callSignJTF = new javax.swing.JTextField();
        electronicPositionDeviceJTF = new javax.swing.JTextField();
        navigationalStatusJTF = new javax.swing.JTextField();
        typeJTF = new javax.swing.JTextField();
        defaultJB = new javax.swing.JButton();
        imageJTF = new javax.swing.JTextField();

        nameJTF.setText(org.openide.util.NbBundle.getMessage(MainShipPanel.class, "MainShipPanel.nameJTF.text")); // NOI18N
        nameJTF.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(MainShipPanel.class, "MainShipPanel.nameJTF.border.title"))); // NOI18N

        mmsiJTF.setText(org.openide.util.NbBundle.getMessage(MainShipPanel.class, "MainShipPanel.mmsiJTF.text")); // NOI18N
        mmsiJTF.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(MainShipPanel.class, "MainShipPanel.mmsiJTF.border.title"))); // NOI18N
        mmsiJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmsiJTFActionPerformed(evt);
            }
        });

        imoJTF.setText(org.openide.util.NbBundle.getMessage(MainShipPanel.class, "MainShipPanel.imoJTF.text")); // NOI18N
        imoJTF.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(MainShipPanel.class, "MainShipPanel.imoJTF.border.title"))); // NOI18N

        widthJTF.setText(org.openide.util.NbBundle.getMessage(MainShipPanel.class, "MainShipPanel.widthJTF.text")); // NOI18N
        widthJTF.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(MainShipPanel.class, "MainShipPanel.widthJTF.border.title"))); // NOI18N
        widthJTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                widthJTFActionPerformed(evt);
            }
        });

        lengthJTF.setText(org.openide.util.NbBundle.getMessage(MainShipPanel.class, "MainShipPanel.lengthJTF.text")); // NOI18N
        lengthJTF.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(MainShipPanel.class, "MainShipPanel.lengthJTF.border.title"))); // NOI18N

        draughtJTF.setText(org.openide.util.NbBundle.getMessage(MainShipPanel.class, "MainShipPanel.draughtJTF.text")); // NOI18N
        draughtJTF.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(MainShipPanel.class, "MainShipPanel.draughtJTF.border.title"))); // NOI18N

        model3DJTF.setText(org.openide.util.NbBundle.getMessage(MainShipPanel.class, "MainShipPanel.model3DJTF.text")); // NOI18N
        model3DJTF.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(MainShipPanel.class, "MainShipPanel.model3DJTF.border.title"))); // NOI18N

        destinationJTF.setText(org.openide.util.NbBundle.getMessage(MainShipPanel.class, "MainShipPanel.destinationJTF.text")); // NOI18N
        destinationJTF.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(MainShipPanel.class, "MainShipPanel.destinationJTF.border.title"))); // NOI18N

        etaJTF.setText(org.openide.util.NbBundle.getMessage(MainShipPanel.class, "MainShipPanel.etaJTF.text")); // NOI18N
        etaJTF.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(MainShipPanel.class, "MainShipPanel.etaJTF.border.title"))); // NOI18N

        callSignJTF.setText(org.openide.util.NbBundle.getMessage(MainShipPanel.class, "MainShipPanel.callSignJTF.text")); // NOI18N
        callSignJTF.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(MainShipPanel.class, "MainShipPanel.callSignJTF.border.title"))); // NOI18N

        electronicPositionDeviceJTF.setText(org.openide.util.NbBundle.getMessage(MainShipPanel.class, "MainShipPanel.electronicPositionDeviceJTF.text")); // NOI18N
        electronicPositionDeviceJTF.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(MainShipPanel.class, "MainShipPanel.electronicPositionDeviceJTF.border.title"))); // NOI18N

        navigationalStatusJTF.setText(org.openide.util.NbBundle.getMessage(MainShipPanel.class, "MainShipPanel.navigationalStatusJTF.text")); // NOI18N
        navigationalStatusJTF.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(MainShipPanel.class, "MainShipPanel.navigationalStatusJTF.border.title"))); // NOI18N

        typeJTF.setText(org.openide.util.NbBundle.getMessage(MainShipPanel.class, "MainShipPanel.typeJTF.text")); // NOI18N
        typeJTF.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(MainShipPanel.class, "MainShipPanel.typeJTF.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(defaultJB, org.openide.util.NbBundle.getMessage(MainShipPanel.class, "MainShipPanel.defaultJB.text")); // NOI18N
        defaultJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultJBActionPerformed(evt);
            }
        });

        imageJTF.setText(org.openide.util.NbBundle.getMessage(MainShipPanel.class, "MainShipPanel.imageJTF.text")); // NOI18N
        imageJTF.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(MainShipPanel.class, "MainShipPanel.imageJTF.border.title"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lengthJTF, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(widthJTF, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imoJTF, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mmsiJTF, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(draughtJTF, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameJTF, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageJTF, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(model3DJTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destinationJTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etaJTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(callSignJTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(electronicPositionDeviceJTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(navigationalStatusJTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeJTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(defaultJB, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {callSignJTF, destinationJTF, electronicPositionDeviceJTF, etaJTF, model3DJTF, navigationalStatusJTF, typeJTF});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mmsiJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(navigationalStatusJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imoJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(electronicPositionDeviceJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(widthJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(callSignJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lengthJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etaJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(draughtJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destinationJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(model3DJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(defaultJB)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mmsiJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmsiJTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mmsiJTFActionPerformed

    private void widthJTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_widthJTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_widthJTFActionPerformed

    private void defaultJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultJBActionPerformed

        nameJTF.setText("Owner");
    }//GEN-LAST:event_defaultJBActionPerformed

    void load() {
        nameJTF.setText(NbPreferences.forModule(MainShipPanel.class).get("name", ""));
        mmsiJTF.setText(NbPreferences.forModule(MainShipPanel.class).get("mmsi", ""));
        imoJTF.setText(NbPreferences.forModule(MainShipPanel.class).get("imo", ""));
        widthJTF.setText(NbPreferences.forModule(MainShipPanel.class).get("width", ""));
        lengthJTF.setText(NbPreferences.forModule(MainShipPanel.class).get("length", ""));
        draughtJTF.setText(NbPreferences.forModule(MainShipPanel.class).get("draught", ""));
        typeJTF.setText(NbPreferences.forModule(MainShipPanel.class).get("type", ""));
        navigationalStatusJTF.setText(NbPreferences.forModule(MainShipPanel.class).get("navigationalStatus", ""));
        electronicPositionDeviceJTF.setText(NbPreferences.forModule(MainShipPanel.class).get("electronicPositionDevice", ""));
        callSignJTF.setText(NbPreferences.forModule(MainShipPanel.class).get("callSign", ""));
        etaJTF.setText(NbPreferences.forModule(MainShipPanel.class).get("eta", ""));
        destinationJTF.setText(NbPreferences.forModule(MainShipPanel.class).get("destination", ""));
        imageJTF.setText(NbPreferences.forModule(MainShipPanel.class).get("image", ""));
    }

    void store() {
        NbPreferences.forModule(MainShipPanel.class).put("name", nameJTF.getText());
        NbPreferences.forModule(MainShipPanel.class).put("mmsi", mmsiJTF.getText());
        NbPreferences.forModule(MainShipPanel.class).put("imo", imoJTF.getText());
        NbPreferences.forModule(MainShipPanel.class).put("width", widthJTF.getText());
        NbPreferences.forModule(MainShipPanel.class).put("length", lengthJTF.getText());
        NbPreferences.forModule(MainShipPanel.class).put("draught", draughtJTF.getText());
        NbPreferences.forModule(MainShipPanel.class).put("type", typeJTF.getText());
        NbPreferences.forModule(MainShipPanel.class).put("navigationalStatus", navigationalStatusJTF.getText());
        NbPreferences.forModule(MainShipPanel.class).put("electronicPositionDevice", electronicPositionDeviceJTF.getText());
        NbPreferences.forModule(MainShipPanel.class).put("callSign", callSignJTF.getText());
        NbPreferences.forModule(MainShipPanel.class).put("eta", etaJTF.getText());
        NbPreferences.forModule(MainShipPanel.class).put("destination", destinationJTF.getText());
        NbPreferences.forModule(MainShipPanel.class).put("image", imageJTF.getText());
        NbPreferences.forModule(MainShipPanel.class).put("3DModel", model3DJTF.getText());
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField callSignJTF;
    private javax.swing.JButton defaultJB;
    private javax.swing.JTextField destinationJTF;
    private javax.swing.JTextField draughtJTF;
    private javax.swing.JTextField electronicPositionDeviceJTF;
    private javax.swing.JTextField etaJTF;
    private javax.swing.JTextField imageJTF;
    private javax.swing.JTextField imoJTF;
    private javax.swing.JTextField lengthJTF;
    private javax.swing.JTextField mmsiJTF;
    private javax.swing.JTextField model3DJTF;
    private javax.swing.JTextField nameJTF;
    private javax.swing.JTextField navigationalStatusJTF;
    private javax.swing.JTextField typeJTF;
    private javax.swing.JTextField widthJTF;
    // End of variables declaration//GEN-END:variables
}
